### ISSUE TITLE
Implementing time based versioning

### ISSUE THREAD

**Issue by davebshow** [ZEROFAIL/goblin-legacy#11]
Hello all,

I wanted to discuss the implementation of time based versioning and get your feedback. After looking through Ian Robinson's Neo4j Time-Based Versioned Graphs blog [1], I think that his approach can be adapted to fit goblin.

I'm not going to summarize the contents of the article, but here are the different options he proposes:
1. Basic model - Identity Nodes, Structural Relationships, State Nodes and Relationships.
2. Linked List - using a linked list structure to order state nodes (allows for sequential state traversal)
3. Current State Relationship - A special rel that points from the ident node to the current state node.
4. Initial State Overload - Overloading ident node with initial state.
5. Current State Overload - Overloading ident node with current state

These options can be combined in a variety of different ways, but not all combinations are possible. All use the Basic Model as a base. Linked Lists can optionally be combined with any possible combination. Possible combos:
1. Current State Relationship
2. Current State Relationship w/Initial State Overload
3. Initial State Overload
4. Current State Overload

Therefore, to implement these combinations, I propose that we provide: a) a new set of kwargs representing these options that will be passed to `Vertex` methods `create`,  `delete`, `save`; and b) a subclass of `Vertex`, `VersionedVertex` that is versioned by default.

The kwargs and defaults would be as follows:

``` python
versioned=False
linked=False
overload_current=False
overload_initial=False
current_state=False
```

In the case that restricted combinations occur, kwargs will be treated as follows:

`versioned=False` overrides all other args
`overload_current=True` overrides `current_state=True`

``` python
if overload_current and overload_initial:
   raise Exception
```

What else do we need? Feedback?
1. http://iansrobinson.com/2014/05/13/time-based-versioned-graphs/

**Comment by jsenecal** [comment]
While I do not see any problem with your proposed solution, I was kinda thinking of a `Mixin` or abstract base classes approach to do the various versionning schemes... 
Yours appears a bit more simple though.

**Comment by davebshow** [comment]
That is definitely possible Jonathan...

We could have something like two mixins:
1. `VersionedMixin`
2. `VersionedLinkedListMixin`

Where `VersionLinkedListMixin` inherits from  `VersionedMixin` with kwargs:

``` python
overload_current=False
overload_initial=False
current_state=False
```

Then, to override versioning we could allow the user to pass:

``` python
versioned=False
```

**Comment by davebshow** [comment]
Though in that case, I think the API should simply provide two classes equivalent to:

``` python
class VersionedVertex(VersionedMixin, Vertex):
    ...

class VersionedLinkedVertex(VersionLinkedListMixin, Vertex):
    ...
```

**Comment by leifurhauks** [comment]
Because the versioning functionality will probably touch a lot of aspects of the implementation, I have a suggestion for a way to do it while keeping the unversioned and versioned classes as decoupled as possible.

If you look at the [custom event loop policy](https://gitlab.zerofail.com/ZEROFAIL/zrpc/blob/develop/tests/conftest.py) I wrote for zrpc, I decided to implement it via composition. This is a pretty simple example and I could have just created a subclass of the default event loop policy, since I only needed to change the `new_event_loop` method and it would probably have been fine. But I decided to go with composition instead, because there was an interface provided (`AbstractEventLoopPolicy`) and because it avoids dynamic inheritance in this case (since the default event loop policy is platform-dependent).

The advantage of this is that the `ZMQEventLoopPolicy` _only_ interacts with the default policy class via the public interface. As long as the default policy never breaks that interface, no changes to the _implementation_ of the default policy can break `ZMQEventLoopPolicy`.

So what I'm getting at is that maybe we can create an abstract base class for vertexes, and then implement the versioning via composition. That way, while we may make changes to the unversioned and versioned vertex classes in parallel, it's easier to keep them from breaking each other.

I became interested in [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) partly from learning a bit of Go earlier this year. Go was designed intentionally to encourage it, by disallowing class-based implementation inheritance altogether, and providing a nifty mechanism to forward method calls to delegates without having to write all the forwarding methods manually.

I also like this post, despite its absurdly sensational title: http://www.javaworld.com/article/2073649/core-java/why-extends-is-evil.html

**Comment by davebshow** [comment]
So @leifurhauks something more like:

``` python

class AbstractBaseVertex:
   ...

@add_metaclass(VertexMetaClass)
class Vertex(AbstractBaseVertex, Element):
    ...

class VersionedVertex(AbstractBaseVertex):
    def __init__(self, *args, **kwargs):
        self.vertex = Vertex(*args, *kwargs)
    ...
```

**Comment by jsenecal** [comment]
@davebshow That's pretty much what I had in mind yes - You were explaining on hangouts that the functinality is mostly covered by groovy scripts though, is that correct? In that case, what would be the best approach?

My guess is that even if they are in fact different groovy scripts, they would still need to be _called_ differently depending on the versionning implementation... Do I make sense ?

**Comment by davebshow** [comment]
Closed due to inactivity.
