### ISSUE TITLE
WTForms Integration

### ISSUE THREAD

**Issue by ghost** [ZEROFAIL/goblin-legacy#28]
Hi guys
Do you plan to add WTForms support?
It would probably take only small modifications as WTForms already has a `populate_obj()` function.
I included a link to screenshots I made to explain how WTForms already works with the ODM MongoEngine, and how it could work with Goblin.
I think Goblin could be one of the first OGM to be interfaced directly to forms, 
I don't think I'm enough skilled to modify Goblin codebase myself thought.

I included screenshots with the most complicated of scenarios (object that contains objects that contains objects)

In this example it is a City containing two Zoos containing Animals

The screenshots are here:

https://imgur.com/a/kFNto

note: 

the mongoengine code shown must use mongoengine==0.8.7 and pymongo==2.8 to work

[test_populate_obj.txt](https://github.com/ZEROFAIL/goblin/files/281408/test_populate_obj.txt)
[test_goblin.txt](https://github.com/ZEROFAIL/goblin/files/281409/test_goblin.txt)

**Comment by leifurhauks** [comment]
We don't currently have plans to be working with WTForms, but in theory it should be possible to use goblin models with WTForms without making the goblin codebase aware of WTForms.

It looks like WTForms should be able to populate goblin properties without any special support, since they are accessed in the usual python way: https://gist.github.com/leifurhauks/5273476cc09d74455b3a24f32a46bb2f

More complex situations (namely relationships) would need some glue, which would be packaged separately from goblin or WTForms, analogous to (for example) the [WTForms-SQLAlchemy](https://github.com/wtforms/wtforms-sqlalchemy) package which adds SQLAlchemy support to WTForms.

In the example you posted, I understand that a City, some Zoos, and some Animals are being created all at once with associated edges. That would probably be relatively straightforward to support; but consider that you might also want a form that adds an Animal to an already existing Zoo (or removes an existing Animal from an existing Zoo). That would presumably mean that forms would have to work with vertex IDs as well.

If you would like to write a third-party package that supports using goblin models with WTForms, we could answer any questions you might have about goblin, and we could potentially put a link to your project from the goblin docs & README. But we won't add integration with any web form packages directly into the core goblin codebase; goblin is intended to be an OGM, not a complete web app framework like Django. Solutions for considerations like forms, de/serialization, and data validation will depend on the application.

**Comment by davebshow** [comment]
+1 @leifurhauks 
@pouledodue As Leif said we will be happy to help you along, but we won't be able to integrate directly in goblin. We appreciate your time and interest!

**Comment by leifurhauks** [comment]
I'm going to close this for now. @pouledodue , if you decide to work on a goblin adapter for WTForms, we'd love to hear about it.
